[package]
name = "gcloud-sdk-signed-url"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
gcloud-sdk = { version = "0.25.8", features = ["google-rest-storage-v1", "google-iam-credentials-v1"] }
regex = "1.11.1"
thiserror = "2.0.3"
url = "2.5.3"
